use zomatodb;

-- 1. List the top 3 customers who have placed the highest number of orders.
SELECT 
    *
FROM
    customer;
SELECT 
    *
FROM
    order_detail;
SELECT 
    c.customer_name AS Customer,
    COUNT(o.customer_id) AS TotalOrders
FROM
    customer AS c
        JOIN
    order_detail AS o ON c.customer_id = o.customer_id
GROUP BY c.customer_name
ORDER BY TotalOrders DESC
LIMIT 3;


-- 2. Find the restaurant that has received the highest average rating.
SELECT 
    restaurant_name, MAX(rrating)
FROM
    restaurant
GROUP BY restaurant_name
LIMIT 1;

-- 3. List all orders from order_detail that were delivered in under 30 minutes.
SELECT 
    order_id,
    timestampdiff(minute,order_time,delivered_time) AS DeliveryTime
FROM
    order_detail
where timestampdiff(minute,order_time,delivered_time) < 30
;


-- 4. Calculate the total revenue generated by each food item. 
-- Display food_id, food_name and Total revenue ordered by total revenue in descending order.

SELECT 
    f.food_id as FoodID, f.food_name AS FoodName,
    SUM(f.price_per_unit * fo.quantity) AS Revenue
FROM
    foods AS f
        JOIN
    order_food AS fo ON f.food_id = fo.food_id
GROUP BY f.food_id, f.food_name
ORDER BY Revenue DESC;

-- 5. Find the second highest revenue-generating restaurant.

SELECT 
    r.restaurant_name AS Restaurant,
    SUM(f.price_per_unit * fo.quantity) AS Revenue
FROM
    restaurant AS r
        JOIN
    order_food AS fo ON r.restaurant_id = fo.restaurant_id
        JOIN
    foods AS f ON f.food_id = fo.food_id
GROUP BY Restaurant
ORDER BY Revenue DESC
LIMIT 1 OFFSET 1;

-- 6. Find the 5 most popular food items based on the quantity sold.

SELECT 
    f.food_id as FoodID, f.food_name AS FoodName,
    SUM(fo.quantity) AS QuantitySold
FROM
    foods AS f
        JOIN
    order_food AS fo ON f.food_id = fo.food_id
GROUP BY f.food_id, f.food_name
ORDER BY QuantitySold DESC
limit 5;

-- 7. List the top 3 Zomato employees with the highest average delivery ratings.
SELECT 
    *
FROM
    zomato_employee;
SELECT 
    employee_name AS Employee,
    employee_avg_rating AS AverageRating
FROM
    zomato_employee
ORDER BY AverageRating DESC
LIMIT 3;

-- 8. Determine the month with the highest number of total orders placed.
SELECT 
    *
FROM
    order_detail;
SELECT 
    MONTHNAME(order_time) AS Month_Name,
    COUNT(order_id) AS Total_Orders
FROM
    order_detail
GROUP BY Month_name
ORDER BY 2 DESC
LIMIT 1;

-- 9. Calculate the average order amount for each customer. Order by average order amount in descending order.

select c.customer_id, c.customer_name, round(avg(f.price_per_unit * fo.quantity),2) AS AvgAmount
from foods as f
join order_food as fo 
join customer as c
on fo.customer_id = c.customer_id
group by c.customer_id, c.customer_name;

-- 10. Identify the most frequent customer for each restaurant.
use zomatodb;
WITH customer_orders AS (
    SELECT
        restaurant_id,
        customer_id,
        COUNT(order_id) AS total_orders,
        
        Row_number() OVER(
            PARTITION BY restaurant_id
            ORDER BY COUNT(order_id) DESC
        ) AS rnk

    FROM order_food
    GROUP BY restaurant_id, customer_id
)

SELECT
    restaurant_id,
    customer_id,
    total_orders
FROM customer_orders
WHERE rnk = 1;

-- 11. Calculate the total number of orders placed on weekends.
SELECT 
    *
FROM
    order_detail;
SELECT 
    DAYNAME(order_time) AS Weekend,
    COUNT(order_id) AS TotalOrders
FROM
    order_detail
WHERE
    DAYNAME(order_time) IN ('Saturday' , 'Sunday')
GROUP BY DAYNAME(order_time);


-- 12. Calculate the average delivery time (in minutes) for orders placed on weekdays versus weekends.


SELECT 
    CASE
        WHEN DAYNAME(order_time) IN ('Saturday' , 'Sunday') THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type,
    ROUND(AVG(TIMESTAMPDIFF(MINUTE,
                order_time,
                delivered_time)),
            2) AS avg_delivery_time_Mins
FROM
    order_detail
WHERE
    delivered_time IS NOT NULL
GROUP BY day_type;

-- 13. List the top 5 most expensive food items. Display food_id, food_name, and price_per_unit for all food items with the highest 5 prices.

WITH food_rank AS (
    SELECT
        *,
        DENSE_RANK() OVER(
            ORDER BY price_per_unit DESC
        ) AS rnk
    FROM foods
)

SELECT *
FROM food_rank
WHERE rnk BETWEEN 1 AND 5;
 
 -- Error Code: 3593. You cannot use the window function 'dense_rank' in this context.'


-- 14. Find the restaurant with the most diverse menu (i.e., the highest number of food items).

SELECT 
    fo.restaurant_id,
    r.restaurant_name,
    COUNT(fo.food_id) AS 'Count of food Items'
FROM
    order_food AS fo
        JOIN
    restaurant AS r ON fo.restaurant_id = r.restaurant_id
GROUP BY restaurant_id
ORDER BY COUNT(fo.food_id) DESC
LIMIT 1;

-- 15. Calculate total payment amount for each payment type.

SELECT 
    p.payment_type,
    SUM(f.price_per_unit * fo.quantity) AS Total_Payment_Amount
FROM
    foods AS f
        JOIN
    order_food AS fo on f.food_id = fo.food_id
    join payment_table as p on p.order_id = fo.order_id
GROUP BY p.payment_type;



